# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17800ff5c78751576638e5d313e289c08cac803af8967e3149627e9a31114cd0d6b0299ee71e5a18690fc65bc52deaf7b4dd007936a12934dbd60f32f0fb8ea7

test:
  secret_key_base: cf99025f392992699ceb53dd65bd6a522e0dd5a7e5a821c5894b8eee4ebf869073a11f893f5b07cbce1cfee884c466fdbe43d98a741af115af7becbda9c7f7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
